### ISSUE TITLE
请问在npm包中使用，优先级还有效吗？

### ISSUE THREAD

**Issue by eminfan** [yusangeng/konph#1]
我在npm包中用了konph，然后在网页html中用了全局配置，不生效。请问如何让npm包中的konph配置生效呢？

**Comment by yusangeng** [comment]
> 我在npm包中用了konph，然后在网页html中用了全局配置，不生效。请问如何让npm包中的konph配置生效呢？

您好，npm中打包这个工具，优先级不受影响。目前也有项目是这样用的。如果不生效的话可以提供一下具体工况。

**Comment by eminfan** [comment]
谢谢。原因找到了，是代码中多个地方同时设置了一个参数名。
